### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by pavel-krivanek** [grascii/editor#3]
When trying to install and run the editor, I found two small issues:

The required version of grascii (0.3.0) needs older grascii-rpc so `requirements.txt ` need to be modifeid this way:
```
grascii-rpc @ git+https://github.com/grascii/rpc.git@e55839ffd99400349bf2da93b86b4c20475dea70
```

To be able to run `transform.py` the directory `grascii/editor/static/data` needs to exist.

**Comment by chanicpanic** [comment]
Thanks for the report! Sorry I missed it for so long.

I believe the issues you encountered are resolved now. Feel free to reopen this issue if that is not the case.
